### ISSUE TITLE
Typescript issues with nuxt

### ISSUE THREAD

**Issue by Suya1671** [ldiebold/firebase-composables#10]
During editing, I currently have 0 typescript types. In webstorm is says that there are no ts types at all

![image](https://user-images.githubusercontent.com/45307955/150201704-dc8cdba4-869a-4b9e-b11a-63a916cdb332.png)

**Comment by Suya1671** [comment]
Seems to be that the TS definition files aren't compiled

**Comment by ldiebold** [comment]
Hi @Suyashtnt! This package was a bit of an experiment, and its successor can be found here.
https://github.com/vueauth/vueauth

However, there are currently no docs and it's in beta.

I'll figure out the right way to archive this project however... feel free to fork it/copy paste the code and make it your own!

**Comment by Suya1671** [comment]
I've made my own version of your code. I'm also planning to make a PR for custom auth

**Comment by ldiebold** [comment]
Fantastic!
And thankyou :pray:
